# Generated by Django 3.1.7 on 2021-03-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordlogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
    ]
