# Generated by Django 3.1.7 on 2021-04-16 01:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='draft_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draftname', models.CharField(max_length=40)),
                ('generation', models.CharField(max_length=10)),
                ('associatedleague', models.IntegerField()),
                ('team', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
            ],
        ),
    ]
