# Generated by Django 3.1.7 on 2021-03-12 22:57

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210312_2240'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.managers.DiscordUserManager()),
            ],
        ),
    ]
