# Generated by Django 3.1.7 on 2021-04-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210407_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='biography',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
