# Generated by Django 3.1.7 on 2021-04-09 04:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210409_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='showdown_alts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
