# Generated by Django 3.1.7 on 2021-05-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210410_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='discordid',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
