# Generated by Django 3.1.7 on 2021-03-17 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_configuration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='abbreviviation',
            new_name='abbreviation',
        ),
    ]
