# Generated by Django 3.1.7 on 2021-03-17 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league_configuration', '0002_auto_20210317_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='moderators',
            field=models.ManyToManyField(related_name='moderating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='league',
            name='host',
        ),
        migrations.AddField(
            model_name='league',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
            preserve_default=False,
        ),
    ]
