# Generated by Django 3.1.7 on 2021-03-19 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_configuration', '0003_auto_20210317_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='league_configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_subleagues', models.IntegerField(default=1)),
                ('allows_cross_subleague_matches', models.BooleanField(default=False)),
                ('teambased', models.BooleanField(default=False)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='league_configuration.league')),
            ],
        ),
    ]
