# Generated by Django 3.1.7 on 2021-03-19 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_configuration', '0004_league_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='subleague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subleague', to='league_configuration.league')),
            ],
        ),
    ]
