# Generated by Django 3.1.7 on 2021-03-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_configuration', '0006_auto_20210319_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='discordserver',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='discordurl',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
