# Generated by Django 3.1.7 on 2021-03-22 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
        ('league_configuration', '0009_remove_league_discordserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='league_pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(default='Banned', max_length=20)),
                ('points', models.IntegerField(null=True)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon')),
                ('subleague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_configuration.subleague')),
            ],
        ),
    ]
