# Generated by Django 3.1.7 on 2021-03-23 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_configuration', '0010_league_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league_pokemon',
            name='subleague',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_list', to='league_configuration.subleague'),
        ),
        migrations.CreateModel(
            name='league_tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(max_length=20)),
                ('points', models.IntegerField(null=True)),
                ('subleague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='league_configuration.subleague')),
            ],
        ),
    ]
