# Generated by Django 3.1.7 on 2021-03-23 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
        ('league_configuration', '0012_auto_20210323_0054'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='league_pokemon',
            unique_together={('subleague', 'pokemon')},
        ),
        migrations.AlterUniqueTogether(
            name='league_tier',
            unique_together={('subleague', 'tier')},
        ),
    ]
