# Generated by Django 3.1.7 on 2021-03-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_configuration', '0013_auto_20210323_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='tier_template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tier', models.CharField(max_length=20)),
                ('points', models.IntegerField(null=True)),
            ],
        ),
    ]
