# Generated by Django 3.1.7 on 2021-03-23 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
        ('league_configuration', '0014_tier_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league_tier',
            options={'ordering': ['-points']},
        ),
        migrations.AddField(
            model_name='tier_template',
            name='pokemon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon'),
            preserve_default=False,
        ),
    ]
