# Generated by Django 3.1.7 on 2021-03-24 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_configuration', '0015_auto_20210323_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules', models.TextField(default='No rules entered')),
                ('subleague', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='league_configuration.subleague')),
            ],
        ),
    ]
