# Generated by Django 3.1.7 on 2021-03-26 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_configuration', '0016_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('draftstart', models.DateTimeField(null=True)),
                ('drafttimer', models.IntegerField(default=12)),
                ('draftbudget', models.IntegerField(default=1000)),
                ('picksperteam', models.IntegerField(default=11)),
                ('drafttype', models.CharField(choices=[('Snake', 'Snake')], default='Snake', max_length=25)),
                ('seasonstart', models.DateTimeField(null=True)),
                ('seasonlength', models.IntegerField(default=7)),
                ('playoffslength', models.IntegerField(default=3)),
                ('freeagenciesallowed', models.IntegerField(default=4)),
                ('tradesallowed', models.IntegerField(default=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subleague', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='league_configuration.subleague')),
            ],
        ),
    ]
