# Generated by Django 3.1.7 on 2021-03-31 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_configuration', '0019_auto_20210327_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='discord_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draftchannel', models.BigIntegerField(null=True)),
                ('replaychannel', models.BigIntegerField(null=True)),
                ('fachannel', models.BigIntegerField(null=True)),
                ('tradechannel', models.BigIntegerField(null=True)),
                ('subleague', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='league_configuration.subleague')),
            ],
        ),
    ]
