# Generated by Django 3.1.7 on 2021-04-02 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_configuration', '0021_auto_20210331_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='subleague',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='league_configuration.subleague'),
        ),
    ]
