# Generated by Django 3.1.7 on 2021-04-05 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_configuration', '0023_league_pokemon_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='league',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='league_configuration.league'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='subleague_name',
            field=models.CharField(default='Main', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='season',
            name='subleague',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasons', to='league_configuration.subleague'),
        ),
    ]
