# Generated by Django 3.1.7 on 2021-04-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_configuration', '0024_auto_20210405_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='subleague_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
