# Generated by Django 3.1.7 on 2021-04-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_configuration', '0025_auto_20210405_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='discord_settings',
            name='server',
            field=models.BigIntegerField(null=True),
        ),
    ]
