# Generated by Django 2.2.10 on 2021-03-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_pokemon_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='sprite',
            field=models.URLField(default='https://claduva.github.io/pdl_images/sprites/default.png'),
        ),
    ]
