# Generated by Django 3.1.7 on 2021-03-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_pokemon_sprite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
