from django.urls import path

from . import views

urlpatterns = [ 
    path("create_league/", views.create_league, name="create_league"),
    path("settings/teams_coaching/", views.teams_coaching, name="teams_coaching"),
    path("settings/teams_coaching/<int:team_id>/", views.team_coaching_settings, name="team_coaching_settings"),
    path("settings/leagues_moderating/", views.leagues_moderating, name="leagues_moderating"),
    path("settings/leagues_moderating/<int:league_id>/", views.league_settings, name="league_settings"),
    path("settings/leagues_moderating/<int:league_id>/configuration/", views.league_configuration, name="league_configuration"),
    path("settings/leagues_moderating/<int:league_id>/configuration/coaches/", views.manage_coaches, name="manage_coaches"),
    path("settings/leagues_moderating/<int:league_id>/configuration/coaches/<int:coach_id>/", views.manage_coach, name="manage_coach"),
    path("settings/leagues_moderating/<int:league_id>/configuration/applications/", views.manage_applications, name="manage_applications"),
    path("settings/leagues_moderating/<int:league_id>/configuration/applications/<int:application_id>/", views.view_application, name="view_application"),
    path("settings/leagues_moderating/<int:league_id>/configuration/applications/<int:application_id>/add/", views.add_to_subleague, name="add_to_subleague"),
    path("settings/leagues_moderating/<int:league_id>/configuration/applications/<int:application_id>/delete/", views.delete_application, name="delete_application"),
    path("settings/leagues_moderating/<int:league_id>/configuration/<int:subleague_id>/", views.subleague_configuration, name="subleague_configuration"),
    path("settings/leagues_moderating/<int:league_id>/configuration/<int:subleague_id>/season/", views.season_configuration, name="season_configuration"),
    path("settings/leagues_moderating/<int:league_id>/configuration/<int:subleague_id>/season/set_draft_order/", views.set_draft_order, name="set_draft_order"),
    path("settings/leagues_moderating/<int:league_id>/configuration/<int:subleague_id>/season/manage_matches/", views.scheduling, name="manage_matches"),
    path("settings/leagues_moderating/<int:league_id>/configuration/<int:subleague_id>/season/manage_matches/edit/<int:match_id>/", views.edit_match, name="edit_match"),
    path("settings/leagues_moderating/<int:league_id>/configuration/<int:subleague_id>/season/manage_matches/delete/<int:match_id>/", views.delete_match, name="delete_match"),
    path("settings/leagues_moderating/<int:league_id>/configuration/<int:subleague_id>/season/manage_matches/round_robin/", views.create_round_robin, name="round_robin"),
    path("settings/leagues_moderating/<int:league_id>/configuration/<int:subleague_id>/season/manage_matches/due_dates/", views.set_due_dates, name="due_dates"),
    path("settings/leagues_moderating/<int:league_id>/configuration/<int:subleague_id>/delete/", views.delete_subleague, name="delete_subleague"),
    path("settings/leagues_moderating/<int:league_id>/configuration/<int:subleague_id>/conferences_and_divisions/", views.subleague_conferences_and_divisions, name="conferences_and_divisions"),
    path("settings/leagues_moderating/<int:league_id>/configuration/<int:subleague_id>/conferences_and_divisions/add_division/", views.add_division, name="add_division"),
    path("settings/leagues_moderating/<int:league_id>/configuration/<int:subleague_id>/conferences_and_divisions/conference/<int:conference_id>/delete/", views.delete_conference, name="delete_conference"),
    path("settings/leagues_moderating/<int:league_id>/configuration/<int:subleague_id>/conferences_and_divisions/division/<int:division_id>/delete/", views.delete_division, name="delete_division"),
    path("settings/leagues_moderating/<int:league_id>/configuration/<int:subleague_id>/rules/", views.subleague_rules, name="subleague_rules"),
    path("settings/leagues_moderating/<int:league_id>/configuration/<int:subleague_id>/manage_tiers/", views.manage_tiers, name="manage_tiers"),
    path("settings/leagues_moderating/<int:league_id>/configuration/<int:subleague_id>/manage_tiers/tiers_from_scratch/", views.tiers_from_scratch, name="tiers_from_scratch"),
    path("settings/leagues_moderating/<int:league_id>/configuration/<int:subleague_id>/manage_tiers/upload_tiers_csv/", views.upload_tiers_csv, name="upload_tiers_csv"),
    path("settings/leagues_moderating/<int:league_id>/configuration/<int:subleague_id>/manage_tiers/tiers_site_template/", views.tiers_site_template, name="tiers_site_template"),
    path("settings/leagues_moderating/<int:league_id>/configuration/<int:subleague_id>/manage_tiers/tiers_other_league/", views.tiers_other_league, name="tiers_other_league"),
    path("settings/leagues_moderating/<int:league_id>/configuration/<int:subleague_id>/manage_tiers/edit_tier/<int:tier_id>/", views.edit_tier, name="edit_tier"),
    path("settings/leagues_moderating/<int:league_id>/configuration/<int:subleague_id>/manage_tiers/delete_tier/<int:tier_id>/", views.delete_tier, name="delete_tier"),
]