# Generated by Django 3.1.7 on 2021-03-31 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league_configuration', '0020_discord_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=50)),
                ('teamabbreviation', models.CharField(max_length=4)),
                ('alternate', models.BooleanField(default=False)),
                ('showdown_username', models.CharField(max_length=50)),
                ('resume', models.TextField()),
                ('replays', models.TextField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_configuration.league')),
                ('subleagues', models.ManyToManyField(to='league_configuration.subleague')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
