# Generated by Django 3.1.7 on 2021-03-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_application_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
