# Generated by Django 3.1.7 on 2021-03-31 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league_configuration', '0021_auto_20210331_2139'),
        ('leagues', '0005_auto_20210331_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=50)),
                ('teamabbreviation', models.CharField(max_length=4)),
                ('logo', models.URLField(blank=True, default='https://media.discordapp.net/attachments/821585145961644062/821585437163782154/genericteam.png', max_length=400)),
                ('conference', models.CharField(max_length=30)),
                ('division', models.CharField(blank=True, max_length=30, null=True)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('forfeits', models.IntegerField(default=0)),
                ('differential', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('support', models.IntegerField(default=0)),
                ('damagedone', models.IntegerField(default=0)),
                ('hphealed', models.IntegerField(default=0)),
                ('luck', models.FloatField(default=0)),
                ('remaininghealth', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_configuration.season')),
                ('user', models.ManyToManyField(related_name='coaching', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
