# Generated by Django 3.1.7 on 2021-04-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_draft_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
