# Generated by Django 3.1.7 on 2021-04-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0010_auto_20210403_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roster',
            old_name='losses',
            new_name='gp',
        ),
        migrations.RenameField(
            model_name='roster',
            old_name='wins',
            new_name='gw',
        ),
    ]
