# Generated by Django 3.1.7 on 2021-04-05 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
        ('leagues', '0011_auto_20210403_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='trading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeeffective', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('executed', models.BooleanField(default=False)),
                ('announced', models.BooleanField(default=False)),
                ('added_pokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_added', to='pokemon.pokemon')),
                ('dropped_pokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_dropped', to='pokemon.pokemon')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.coach')),
            ],
        ),
        migrations.CreateModel(
            name='trade_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offeredpokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered', to='leagues.roster')),
                ('requestedpokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested', to='leagues.roster')),
            ],
        ),
        migrations.CreateModel(
            name='free_agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeeffective', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('executed', models.BooleanField(default=False)),
                ('announced', models.BooleanField(default=False)),
                ('added_pokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fa_added', to='pokemon.pokemon')),
                ('dropped_pokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fa_dropped', to='pokemon.pokemon')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.coach')),
            ],
        ),
    ]
