# Generated by Django 3.1.7 on 2021-04-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0012_free_agency_trade_request_trading'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade_request',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
