# Generated by Django 3.1.7 on 2021-04-05 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0013_trade_request_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(null=True)),
                ('playoff_week', models.CharField(max_length=30, null=True)),
                ('duedate', models.DateTimeField(null=True)),
                ('team1score', models.IntegerField(default=0)),
                ('team2score', models.IntegerField(default=0)),
                ('replay', models.CharField(max_length=200, null=True)),
                ('data', models.JSONField(null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('announced', models.BooleanField(default=False)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='leagues.coach')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='leagues.coach')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='leagues.coach')),
            ],
        ),
    ]
