# Generated by Django 3.1.7 on 2021-04-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0014_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='playoff_week',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
