# Generated by Django 3.1.7 on 2021-04-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0015_auto_20210407_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade_request',
            name='sent',
        ),
    ]
