# Generated by Django 3.1.7 on 2021-04-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0016_remove_trade_request_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='trading',
            name='weekeffective',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
