# Generated by Django 3.1.7 on 2021-04-08 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
        ('leagues', '0017_trading_weekeffective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='free_agency',
            name='added_pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fa_added', to='pokemon.pokemon'),
        ),
        migrations.AlterField(
            model_name='free_agency',
            name='dropped_pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fa_dropped', to='pokemon.pokemon'),
        ),
        migrations.AlterField(
            model_name='trading',
            name='added_pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_added', to='pokemon.pokemon'),
        ),
        migrations.AlterField(
            model_name='trading',
            name='dropped_pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_dropped', to='pokemon.pokemon'),
        ),
    ]
