# Generated by Django 3.1.7 on 2021-04-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0019_free_agency_weekeffective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='conference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
