# Generated by Django 3.1.7 on 2022-04-02 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
        ('leagues', '0020_auto_20210410_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('picktime', models.DateTimeField(auto_now=True, null=True)),
                ('announced', models.BooleanField(default=False)),
                ('pokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemon')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='leagues.coach')),
            ],
        ),
    ]
