# Generated by Django 3.1.7 on 2022-04-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0021_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='outbid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField(null=True, unique=True)),
                ('text', models.CharField(max_length=200)),
                ('announced', models.BooleanField(default=False)),
            ],
        ),
    ]
