# Generated by Django 3.1.7 on 2022-04-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0022_outbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbid',
            name='user',
            field=models.BigIntegerField(),
        ),
    ]
